export const SCENARIOS = [
  {
    id: 'kindred-technology',
    emoji: '💻',
    label: 'Kindred Technology',
    businessName: 'Kindred Technology Group',
    industry: 'Web Design & Digital Marketing',
    context: 'We are a full-service web design, development, and digital marketing agency with over 10 years of experience. We offer website development, SEO, branding, content development, mobile app development, e-commerce, and hosting. We serve small businesses, startups, and Fortune 500 companies. Located in Montgomery, Alabama.',
    phone: '(833) 354-6373',
    email: 'success@kindredtechnology.com',
    address: '3066 Zelda Rd #354, Montgomery, AL 36106',
    hours: 'Mon-Fri 9am-5pm',
    website: 'https://kindredtechnology.com',
    color: '#4F46E5',
    gradient: 'from-indigo-600 to-violet-600',
    gradientCSS: 'linear-gradient(135deg, #4F46E5, #7C3AED)',
    tagline: 'Full-service digital agency with 10+ years of excellence',
    logo: 'https://www.google.com/s2/favicons?domain=kindredtechnology.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    services: ['Web Development', 'SEO', 'Branding', 'Mobile Apps', 'E-Commerce'],
    quickReplies: [
      'I need a new website for my small business',
      'We want to improve our Google rankings with SEO',
      'Can you redesign our current site and logo?',
    ],
  },
  {
    id: 'baker-underwood-law',
    emoji: '⚖️',
    label: 'Baker Underwood Law',
    businessName: 'The Baker Underwood Law Firm',
    industry: 'Law Firm',
    context: 'We are a boutique law firm founded in 2018 by Adele Baker Underwood. We specialize in criminal defense, business litigation, business formation, juvenile justice, cannabis law, family law, probate, estates, trusts, and tax. We focus on protecting children, juveniles, and families. Located in Montgomery, Alabama.',
    phone: '(334) 549-3622',
    email: 'info@bakerunderwoodlaw.com',
    address: 'Montgomery, AL 36104',
    hours: 'Mon-Thu 9am-5pm, Fri 9am-3pm',
    website: 'https://adeleunderwood.com',
    color: '#7C3AED',
    gradient: 'from-violet-600 to-purple-700',
    gradientCSS: 'linear-gradient(135deg, #7C3AED, #6D28D9)',
    tagline: 'Protecting families, juveniles, and your future since 2018',
    logo: 'https://www.google.com/s2/favicons?domain=adeleunderwood.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
    services: ['Criminal Defense', 'Business Litigation', 'Family Law', 'Probate & Estates', 'Cannabis Law'],
    quickReplies: [
      'I need help forming an LLC for my new business',
      'Can I schedule a consultation about a family law matter?',
      'I have a probate question about my late parent\'s estate',
    ],
  },
  {
    id: 'walker360',
    emoji: '🖨️',
    label: 'Walker360',
    businessName: 'Walker360',
    industry: 'Commercial Printing & Marketing',
    context: 'We are a full-service commercial printing company with over 75 years of experience and a 40,000 sq ft facility. We offer digital printing, offset printing, wide format printing, direct mail marketing, 24/7 print-on-demand, binding and finishing, business stationery, website development, and digital advertising. We are in the Top 1% of printing companies nationally. Serving Montgomery, Birmingham, Atlanta and surrounding areas.',
    phone: '(334) 832-4975',
    email: 'info@walker360.com',
    address: '2501 East 5th Street, Montgomery, AL 36107',
    hours: 'Mon-Fri 8am-5pm (warehouse 24/7)',
    website: 'https://walker360.com',
    color: '#DC2626',
    gradient: 'from-red-600 to-rose-600',
    gradientCSS: 'linear-gradient(135deg, #DC2626, #E11D48)',
    tagline: 'Top 1% printing company — 75+ years of experience',
    logo: 'https://www.google.com/s2/favicons?domain=walker360.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?w=800&q=80',
    services: ['Digital Printing', 'Offset Printing', 'Direct Mail', 'Wide Format', 'Design Services'],
    quickReplies: [
      'I need 5,000 brochures printed for a trade show next week',
      'Can you handle a direct mail campaign for 10,000 addresses?',
      'I need business cards and letterhead designed and printed',
    ],
  },
  {
    id: 'slt-consulting',
    emoji: '📊',
    label: 'SLT Consulting',
    businessName: 'SLT Business Consulting',
    industry: 'Business Consulting',
    context: 'We help small businesses and entrepreneurs turn their innovative ideas and skills into a business. We help put together strategic game plans to launch businesses and create blueprints to help create capital to scale. We offer Business Audit Consults, Business Discovery Consults, and Money Magnet Strategy Consults. Located in Montgomery, Alabama.',
    phone: '(866) 444-3944',
    email: 'info@sltbusinessconsulting.com',
    address: '7806 Vaughn Rd #1169, Montgomery, AL 36116',
    hours: 'Mon-Fri 9am-5pm',
    website: 'https://www.sltbusinessconsulting.com',
    color: '#0891B2',
    gradient: 'from-cyan-600 to-teal-600',
    gradientCSS: 'linear-gradient(135deg, #0891B2, #0D9488)',
    tagline: 'Turning innovative ideas into thriving businesses',
    logo: 'https://www.google.com/s2/favicons?domain=sltbusinessconsulting.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80',
    services: ['Business Audit', 'Discovery Consults', 'Money Magnet Strategy', 'Launch Planning', 'Capital Strategy'],
    quickReplies: [
      'I have a business idea but don\'t know where to start',
      'I need help scaling my small business to the next level',
      'Can I book a discovery call to discuss my startup?',
    ],
  },
  {
    id: 'pathway-consult',
    emoji: '🧭',
    label: 'Pathway Consult',
    businessName: 'Pathway Small Business Consultants',
    industry: 'Small Business Consulting',
    context: 'We specialize in empowering startups and small businesses with 20 or fewer employees to achieve their full potential. With over 18 years of firsthand experience running and growing a successful business, we offer practical, personalized consulting to clarify goals, optimize operations, and grow with confidence. We offer hourly consulting and monthly retainer options.',
    phone: '(256) 555-0199',
    email: 'info@pathwaybusinessconsult.com',
    address: 'Alabama',
    hours: 'Mon-Fri 9am-5pm',
    website: 'https://www.pathwaybusinessconsult.com',
    color: '#059669',
    gradient: 'from-emerald-600 to-green-600',
    gradientCSS: 'linear-gradient(135deg, #059669, #16A34A)',
    tagline: '18+ years empowering startups to reach their full potential',
    logo: 'https://www.google.com/s2/favicons?domain=pathwaybusinessconsult.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
    services: ['Hourly Consulting', 'Monthly Retainer', 'Goal Clarity', 'Operations Optimization', 'Growth Strategy'],
    quickReplies: [
      'I just started a business with 5 employees and need guidance',
      'Can I book the free 15-minute consultation?',
      'I need help optimizing my operations and reducing costs',
    ],
  },
  {
    id: 'veda-cuisine',
    emoji: '🍛',
    label: 'Veda Indian Cuisine',
    businessName: 'VEDA Indian Cuisine & Bar',
    industry: 'Indian Restaurant & Bar',
    context: 'We are a premier Indian restaurant and bar in Huntsville, Alabama serving authentic Indian cuisine. We offer dine-in, takeout, and delivery. Our menu features a wide selection of traditional Indian dishes, appetizers, entrees, biryani, bread, and specialty cocktails. We are closed on Mondays.',
    phone: '(256) 585-2552',
    email: 'info@thevedausa.com',
    address: '4874 University Drive, Huntsville, AL 35816',
    hours: 'Tue-Sun: Lunch 11am-2:30pm, Dinner 5pm-9:30pm. Closed Monday.',
    website: 'https://thevedausa.com',
    color: '#D97706',
    gradient: 'from-amber-600 to-orange-600',
    gradientCSS: 'linear-gradient(135deg, #D97706, #EA580C)',
    tagline: 'Authentic Indian cuisine & specialty cocktails in Huntsville',
    logo: 'https://www.google.com/s2/favicons?domain=thevedausa.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    services: ['Dine-In', 'Takeout', 'Delivery', 'Catering', 'Private Events'],
    quickReplies: [
      'Do you have a table for 4 available tonight at 7pm?',
      'Can I place a large takeout order for 20 people?',
      'Do you offer catering for private events?',
    ],
  },
  {
    id: 'society-salon',
    emoji: '💇',
    label: 'Society Salon',
    businessName: 'Society Salon',
    industry: 'Hair Salon & Spa',
    context: 'We are a voted top salon and spa in Huntsville, Alabama. We offer balayage coloring, hair cuts, fashion colors, luxury hair extensions, blow outs, perms, keratin treatments, lash lifts, lash tints, lash extensions, facials, hydrafacials, dermaplaning, microdermabrasion, facial waxing, brow lamination, henna brows, and makeup artist services for events.',
    phone: '(256) 665-3651',
    email: 'info@societysalonal.com',
    address: '20 Town Center Dr NW, Suite 1111, Huntsville, AL 35806',
    hours: 'Mon-Fri 8:30am-8:30pm, Sat 9am-6pm',
    website: 'https://www.societysalonal.com',
    color: '#EC4899',
    gradient: 'from-pink-500 to-rose-500',
    gradientCSS: 'linear-gradient(135deg, #EC4899, #F43F5E)',
    tagline: 'Voted top salon & spa in Huntsville, Alabama',
    logo: 'https://www.google.com/s2/favicons?domain=societysalonal.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80',
    services: ['Balayage & Color', 'Haircuts', 'Extensions', 'Facials & Hydrafacials', 'Bridal Services'],
    quickReplies: [
      'I want to book a balayage and blowout for this Saturday',
      'Do you have any openings for a hydrafacial this week?',
      'I need bridal hair and makeup for my wedding party of 6',
    ],
  },
  {
    id: 'mr-rooter',
    emoji: '🔧',
    label: 'Mr. Rooter Plumbing',
    businessName: 'Mr. Rooter Plumbing of Huntsville',
    industry: 'Plumbing Services',
    context: 'We are a locally-owned plumbing company serving Huntsville, AL and surrounding areas since 1990. We handle sewer backup, leaking or frozen pipes, clogged drains, water heater repair, drain cleaning, septic tank services, and all residential and commercial plumbing needs. We offer 24/7 emergency service.',
    phone: '(256) 574-4710',
    email: 'info@mrrooter.com',
    address: '1330 Fletcher Dr, Huntsville, AL 35801',
    hours: 'Open 24/7',
    website: 'https://www.mrrooter.com/huntsville/',
    color: '#EA580C',
    gradient: 'from-orange-600 to-red-600',
    gradientCSS: 'linear-gradient(135deg, #EA580C, #DC2626)',
    tagline: '24/7 emergency plumbing — serving Huntsville since 1990',
    logo: 'https://www.google.com/s2/favicons?domain=mrrooter.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=800&q=80',
    services: ['Emergency Service', 'Drain Cleaning', 'Water Heater Repair', 'Sewer Backup', 'Repiping'],
    bookingProfile: {
      timezone: 'America/Chicago',
      slotMinutes: 30,
      defaultDurationMinutes: 90,
      workingHours: {
        0: { start: '08:00', end: '13:00' },
        1: { start: '07:00', end: '18:00' },
        2: { start: '07:00', end: '18:00' },
        3: { start: '07:00', end: '18:00' },
        4: { start: '07:00', end: '18:00' },
        5: { start: '07:00', end: '18:00' },
        6: { start: '08:00', end: '14:00' },
      },
    },
    quickReplies: [
      'I have a burst pipe flooding my kitchen right now!',
      'My water heater stopped working, can someone come today?',
      'I need a quote for a whole-house repiping job',
    ],
  },
  {
    id: 'inspiring-smiles',
    emoji: '🦷',
    label: 'Inspiring Smiles Dental',
    businessName: 'Inspiring Smiles Family Dentistry',
    industry: 'Family Dentistry',
    context: 'We are a family dental practice in Huntsville, Alabama offering comprehensive dental care for patients of all ages. Our services include general dentistry, cleanings, fillings, crowns, bridges, teeth whitening, pediatric dentistry, and emergency dental care. We focus on creating a comfortable, welcoming environment.',
    phone: '(256) 852-6161',
    email: 'info@inspiringsmilesdental.com',
    address: '2585 Sparkman Dr, Huntsville, AL 35810',
    hours: 'Mon-Thu 8am-5pm. Fri-Sun Closed.',
    website: 'https://www.inspiringsmilesdental.com',
    color: '#2563EB',
    gradient: 'from-blue-600 to-sky-600',
    gradientCSS: 'linear-gradient(135deg, #2563EB, #0284C7)',
    tagline: 'Comprehensive family dental care in a welcoming environment',
    logo: 'https://www.google.com/s2/favicons?domain=inspiringsmilesdental.com&sz=128',
    heroImage: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800&q=80',
    services: ['General Dentistry', 'Teeth Whitening', 'Pediatric Dentistry', 'Crowns & Bridges', 'Emergency Care'],
    quickReplies: [
      'I need to schedule a cleaning and checkup for my family',
      'I chipped a tooth and need an emergency appointment',
      'Do you accept Blue Cross Blue Shield dental insurance?',
    ],
  },
]

export function getScenario(id) {
  return SCENARIOS.find(s => s.id === id) || SCENARIOS[0]
}

export function getScenarioBySlug(slug) {
  return SCENARIOS.find(s => s.id === slug) || null
}

export default SCENARIOS
